### ISSUE TITLE
Error when removing obsolete flows

### ISSUE THREAD

**Issue by spw-dhurran** [hardisgroupcom/sfdx-hardis#662] opened 2024-07-30 16:18 UTC
? 🦙 Do you confirm you want to delete these 46 flow versions ? ✅ Yes
[sfdx-hardis] Error deleting Flow records:[object Object]
SfdxError: Error deleting Flow records:[object Object]
    at handleCallback (/Users/firstname.lastname/.local/share/sf/node_modules/sfdx-hardis/lib/common/utils/apiUtils.js:122:23)
    at /Users/firstname.lastname/.local/share/sf/node_modules/sfdx-hardis/node_modules/jsforce/lib/promise.js:76:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
ERROR running hardis:org:purge:flow:  Cannot read properties of undefined (reading '_toRecordResult')
[sfdx-hardis] hardis:org:purge:flow execution time 0:00:44.509

<img width="338" alt="image" src="https://github.com/user-attachments/assets/d560667c-2ef1-4231-bfe4-eb2b36fe1e80">

Node Version v20.8.0
git version 2.39.3 (Apple Git-146)

**Comment by spw-dhurran** [comment] 2024-07-30 16:29
Sorry wrong repo

**Comment by nvuillam** [comment] 2024-07-30 18:06
This is the good repo, as this is the command called from VsCode sfdx-hardis :)

I'll have a look :)

**Comment by nvuillam** [comment] 2024-08-06 16:09
@spw-dhurran I did not succeed to reproduce the issue

Do you have on all orgs or just a single one ?

The error seems to be with Bulk API:
- Do you have the appropriate permissions (Flow User on your User) ?
- Are you system admin ?

**Comment by spw-dhurran** [comment] 2024-08-07 08:20
Hi @nvuillam, yes it doesn't fail if I try and delete say 5 flows. I have it on all orgs. My colleague also installed and had the same issue, we are both sys admins. I wonder if something is being blocked by the company. When it fails it actually deletes some, then blows up coming back for the next batch. This is a recent thing.

**Comment by nvuillam** [comment] 2024-08-11 08:08
@spw-dhurran when you say "recent", does it mean "since the beginning of june", or later ?

We published an update to dramatically improve the execution time for the command in https://github.com/hardisgroupcom/sfdx-hardis/pull/617

**Comment by spw-dhurran** [comment] 2024-08-12 08:16
Hi @nvuillam he installed the start of August, after I had this issue.

**Comment by nvuillam** [comment] 2024-08-12 08:52
@spw-dhurran please can you have a look in Bulk Data Load Jobs in the setup to check if you see any errors ?

https://help.salesforce.com/s/articleView?id=sf.monitoring_async_api_jobs_details.htm&type=5

**Comment by spw-dhurran** [comment] 2024-08-12 09:31
Hi @nvuillam  I just ran it again, with 14 obsolete flows, no new record in bulk jobs
![image](https://github.com/user-attachments/assets/c3b983a6-aff5-44d5-bbc8-caba6960aaa3)

**Comment by nvuillam** [comment] 2024-08-12 09:33
Lightning URI event is a table from event monitoring, so indeed it's something else...

@masaner did you see such issues when you implemented the refactoring of the command ?

**Comment by masaner** [comment] 2024-08-12 09:38
> Lightning URI event is a table from event monitoring, so indeed it's something else...
> 
> @masaner did you see such issues when you implemented the refactoring of the command ?

Hey @nvuillam i did not see any issues while i was doing the refactoring. I did some tests and confirmed that the changes were functioning correctly. I can take another look at it if need be.

**Comment by nvuillam** [comment] 2024-09-07 20:15
@spw-dhurran the problem has been declared to jsforce and is in current investigation -> https://github.com/jsforce/jsforce/issues/1571

I added a failsafe that runs the deletion one by one in casse the bulk delete fails: it's longer but it works :)

It will be released in sfdx-hardis v5, but you can already test it using `sf plugins install sfdx-hardis@alpha` :)

Note: I also added an enhancement that also deletes (after prompting user)  the FlowInterviews that would prevent Flow Versions deletions

**Closed** 2024-09-23 06:44 UTC
Labels: v5

**Comment by spw-dhurran** [comment] 2024-09-23 08:23
Thanks Nicolas @nvuillam
